import { WordPair } from './types';

export const ENGLISH_WORD_LIST: WordPair[] = [
    // Food & Drink
    { general: "Fruit", specific: "Banana" },
    { general: "Fruit", specific: "Apple" },
    { general: "Fruit", specific: "Watermelon" },
    { general: "Fruit", specific: "Grape" },
    { general: "Fruit", specific: "Strawberry" },
    { general: "Fruit", specific: "Pineapple" },
    { general: "Vegetable", specific: "Carrot" },
    { general: "Vegetable", specific: "Potato" },
    { general: "Vegetable", specific: "Broccoli" },
    { general: "Vegetable", specific: "Onion" },
    { general: "Drink", specific: "Coffee" },
    { general: "Drink", specific: "Tea" },
    { general: "Drink", specific: "Orange Juice" },
    { general: "Drink", specific: "Milkshake" },
    { general: "Fast Food", specific: "Pizza" },
    { general: "Fast Food", specific: "Burger" },
    { general: "Fast Food", specific: "Fries" },
    { general: "Fast Food", specific: "Taco" },
    { general: "Dessert", specific: "Ice Cream" },
    { general: "Dessert", specific: "Cake" },
    { general: "Dessert", specific: "Donut" },
    { general: "Dessert", specific: "Cookie" },
    { general: "Breakfast", specific: "Cereal" },
    { general: "Breakfast", specific: "Pancakes" },
    { general: "Breakfast", specific: "Eggs" },
    { general: "Spice", specific: "Pepper" },
    { general: "Spice", specific: "Salt" },
    { general: "Candy", specific: "Chocolate" },
    { general: "Candy", specific: "Lollipop" },
    { general: "Soda", specific: "Coca-Cola" },
    { general: "Soda", specific: "Sprite" },

    // Animals
    { general: "Animal", specific: "Elephant" },
    { general: "Animal", specific: "Lion" },
    { general: "Animal", specific: "Tiger" },
    { general: "Animal", specific: "Giraffe" },
    { general: "Animal", specific: "Zebra" },
    { general: "Pet", specific: "Dog" },
    { general: "Pet", specific: "Cat" },
    { general: "Pet", specific: "Hamster" },
    { general: "Farm Animal", specific: "Cow" },
    { general: "Farm Animal", specific: "Pig" },
    { general: "Farm Animal", specific: "Sheep" },
    { general: "Farm Animal", specific: "Chicken" },
    { general: "Bird", specific: "Penguin" },
    { general: "Bird", specific: "Eagle" },
    { general: "Bird", specific: "Parrot" },
    { general: "Bird", specific: "Owl" },
    { general: "Insect", specific: "Ant" },
    { general: "Insect", specific: "Bee" },
    { general: "Insect", specific: "Butterfly" },
    { general: "Insect", specific: "Spider" },
    { general: "Fish", specific: "Shark" },
    { general: "Fish", specific: "Goldfish" },
    { general: "Fish", specific: "Whale" },
    { general: "Reptile", specific: "Snake" },
    { general: "Reptile", specific: "Turtle" },
    { general: "Reptile", specific: "Crocodile" },

    // Places
    { general: "Country", specific: "Japan" },
    { general: "Country", specific: "USA" },
    { general: "Country", specific: "India" },
    { general: "Country", specific: "Brazil" },
    { general: "Country", specific: "France" },
    { general: "City", specific: "Paris" },
    { general: "City", specific: "New York" },
    { general: "City", specific: "London" },
    { general: "City", specific: "Tokyo" },
    { general: "Continent", specific: "Africa" },
    { general: "Continent", specific: "Asia" },
    { general: "Planet", specific: "Mars" },
    { general: "Planet", specific: "Earth" },
    { general: "Planet", specific: "Jupiter" },
    { general: "Tourist Attraction", specific: "Eiffel Tower" },
    { general: "Tourist Attraction", specific: "Statue of Liberty" },
    { general: "Tourist Attraction", specific: "Pyramids" },
    { general: "Tourist Attraction", specific: "Taj Mahal" },
    { general: "Room", specific: "Kitchen" },
    { general: "Room", specific: "Bathroom" },
    { general: "Room", specific: "Bedroom" },

    // Objects & Household
    { general: "Furniture", specific: "Chair" },
    { general: "Furniture", specific: "Sofa" },
    { general: "Furniture", specific: "Bed" },
    { general: "Furniture", specific: "Table" },
    { general: "Tool", specific: "Hammer" },
    { general: "Tool", specific: "Screwdriver" },
    { general: "Tool", specific: "Saw" },
    { general: "Clothing", specific: "Hat" },
    { general: "Clothing", specific: "T-Shirt" },
    { general: "Clothing", specific: "Jeans" },
    { general: "Clothing", specific: "Shoes" },
    { general: "Clothing", specific: "Socks" },
    { general: "Appliance", specific: "Microwave" },
    { general: "Appliance", specific: "Refrigerator" },
    { general: "Appliance", specific: "Toaster" },
    { general: "Appliance", specific: "Washing Machine" },
    { general: "Kitchen Item", specific: "Fork" },
    { general: "Kitchen Item", specific: "Spoon" },
    { general: "Kitchen Item", specific: "Knife" },
    { general: "Kitchen Item", specific: "Cup" },
    { general: "Bathroom Item", specific: "Toothbrush" },
    { general: "Bathroom Item", specific: "Soap" },
    { general: "Bathroom Item", specific: "Towel" },
    { general: "Electronic", specific: "Laptop" },
    { general: "Electronic", specific: "Phone" },
    { general: "Electronic", specific: "Television" },
    { general: "Electronic", specific: "Camera" },

    // Modern & Tech
    { general: "App", specific: "TikTok" },
    { general: "App", specific: "Instagram" },
    { general: "App", specific: "WhatsApp" },
    { general: "Website", specific: "Google" },
    { general: "Website", specific: "YouTube" },
    { general: "Website", specific: "Wikipedia" },
    { general: "Company", specific: "Apple" },
    { general: "Company", specific: "Microsoft" },
    { general: "Company", specific: "Tesla" },
    { general: "Company", specific: "Nike" },

    // Things
    { general: "Vehicle", specific: "Bicycle" },
    { general: "Vehicle", specific: "Car" },
    { general: "Vehicle", specific: "Airplane" },
    { general: "Vehicle", specific: "Train" },
    { general: "Vehicle", specific: "Boat" },
    { general: "Musical Instrument", specific: "Guitar" },
    { general: "Musical Instrument", specific: "Piano" },
    { general: "Musical Instrument", specific: "Drums" },
    { general: "Musical Instrument", specific: "Violin" },
    { general: "Weapon", specific: "Sword" },
    { general: "Weapon", specific: "Gun" },
    { general: "Weapon", specific: "Bow and Arrow" },
    { general: "Toy", specific: "Lego" },
    { general: "Toy", specific: "Doll" },
    { general: "Toy", specific: "Ball" },
    { general: "School Supply", specific: "Pencil" },
    { general: "School Supply", specific: "Notebook" },
    { general: "School Supply", specific: "Backpack" },
    { general: "School Supply", specific: "Eraser" },

    // Concepts & Media
    { general: "Movie", specific: "Titanic" },
    { general: "Movie", specific: "Avatar" },
    { general: "Movie", specific: "Star Wars" },
    { general: "Board Game", specific: "Monopoly" },
    { general: "Board Game", specific: "Chess" },
    { general: "Video Game", specific: "Minecraft" },
    { general: "Video Game", specific: "Mario" },
    { general: "Video Game", specific: "Fortnite" },
    { general: "Job", specific: "Doctor" },
    { general: "Job", specific: "Teacher" },
    { general: "Job", specific: "Police Officer" },
    { general: "Job", specific: "Firefighter" },
    { general: "Job", specific: "Chef" },
    { general: "Sport", specific: "Soccer" },
    { general: "Sport", specific: "Basketball" },
    { general: "Sport", specific: "Tennis" },
    { general: "Sport", specific: "Swimming" },
    { general: "Holiday", specific: "Christmas" },
    { general: "Holiday", specific: "Halloween" },
    { general: "Holiday", specific: "Easter" },
    { general: "Emotion", specific: "Happiness" },
    { general: "Emotion", specific: "Anger" },
    { general: "Emotion", specific: "Fear" },
    { general: "Superhero", specific: "Batman" },
    { general: "Superhero", specific: "Superman" },
    { general: "Superhero", specific: "Spider-Man" },
    { general: "Musician", specific: "Taylor Swift" },
    { general: "Musician", specific: "Michael Jackson" },
    { general: "Fictional Character", specific: "Harry Potter" },
    { general: "Fictional Character", specific: "Sherlock Holmes" },
    { general: "TV Show", specific: "Friends" },
    { general: "TV Show", specific: "Squid Game" },
    { general: "Language", specific: "Spanish" },
    { general: "Language", specific: "English" },
    
    // Nature
    { general: "Weather", specific: "Rain" },
    { general: "Weather", specific: "Snow" },
    { general: "Weather", specific: "Sun" },
    { general: "Weather", specific: "Tornado" },
    { general: "Tree", specific: "Oak" },
    { general: "Tree", specific: "Palm Tree" },
    { general: "Flower", specific: "Rose" },
    { general: "Flower", specific: "Sunflower" },
    { general: "Flower", specific: "Tulip" },
    { general: "Body Part", specific: "Hand" },
    { general: "Body Part", specific: "Foot" },
    { general: "Body Part", specific: "Eye" },
    { general: "Body Part", specific: "Heart" },
    { general: "Color", specific: "Blue" },
    { general: "Color", specific: "Red" },
    { general: "Color", specific: "Green" },
    { general: "Color", specific: "Yellow" },
    { general: "Natural Disaster", specific: "Earthquake" },
    { general: "Natural Disaster", specific: "Volcano" },
    { general: "Natural Disaster", specific: "Tsunami" },
    { general: "Element", specific: "Fire" },
    { general: "Element", specific: "Water" }
];

export const MALAYALAM_WORD_LIST: WordPair[] = [
    // Food
    { general: "പഴം (Fruit)", specific: "മാങ്ങ (Mango)" },
    { general: "പഴം (Fruit)", specific: "ചക്ക (Jackfruit)" },
    { general: "പഴം (Fruit)", specific: "വാഴപ്പഴം (Banana)" },
    { general: "പഴം (Fruit)", specific: "കൈതച്ചക്ക (Pineapple)" },
    { general: "പഴം (Fruit)", specific: "മുന്തിരി (Grape)" },
    { general: "പച്ചക്കറി (Vegetable)", specific: "വെണ്ടയ്ക്ക (Okra)" },
    { general: "പച്ചക്കറി (Vegetable)", specific: "തക്കാളി (Tomato)" },
    { general: "പച്ചക്കറി (Vegetable)", specific: "ഉള്ളി (Onion)" },
    { general: "പച്ചക്കറി (Vegetable)", specific: "മുളക് (Chilli)" },
    { general: "ഭക്ഷണം (Food)", specific: "ബിരിയാണി (Biriyani)" },
    { general: "ഭക്ഷണം (Food)", specific: "ദോശ (Dosa)" },
    { general: "ഭക്ഷണം (Food)", specific: "പുട്ട് (Puttu)" },
    { general: "ഭക്ഷണം (Food)", specific: "അപ്പം (Appam)" },
    { general: "ഭക്ഷണം (Food)", specific: "കഞ്ഞി (Rice Porridge)" },
    { general: "ഭക്ഷണം (Food)", specific: "സദ്യ (Sadya)" },
    { general: "ഭക്ഷണം (Food)", specific: "ഇഡ്ഡലി (Idli)" },
    { general: "പാനീയം (Drink)", specific: "ചായ (Tea)" },
    { general: "പാനീയം (Drink)", specific: "കാപ്പി (Coffee)" },
    { general: "പാനീയം (Drink)", specific: "കരിരിക്ക് (Tender Coconut)" },
    { general: "പാനീയം (Drink)", specific: "സംഭാരം (Spiced Buttermilk)" },
    { general: "മധുരം (Sweet)", specific: "പായസം (Payasam)" },
    { general: "മധുരം (Sweet)", specific: "ലഡു (Laddu)" },

    // Animals & Nature
    { general: "മൃഗം (Animal)", specific: "ആന (Elephant)" },
    { general: "മൃഗം (Animal)", specific: "പൂച്ച (Cat)" },
    { general: "മൃഗം (Animal)", specific: "പട്ടി (Dog)" },
    { general: "മൃഗം (Animal)", specific: "പശു (Cow)" },
    { general: "മൃഗം (Animal)", specific: "കടുവ (Tiger)" },
    { general: "മൃഗം (Animal)", specific: "സിംഹം (Lion)" },
    { general: "പക്ഷി (Bird)", specific: "മയിൽ (Peacock)" },
    { general: "പക്ഷി (Bird)", specific: "കാക്ക (Crow)" },
    { general: "പക്ഷി (Bird)", specific: "കോഴി (Chicken)" },
    { general: "പക്ഷി (Bird)", specific: "തത്ത (Parrot)" },
    { general: "പ്രാണി (Insect)", specific: "ഈച്ച (Fly)" },
    { general: "പ്രാണി (Insect)", specific: "കൊതുക് (Mosquito)" },
    { general: "പ്രാണി (Insect)", specific: "ഉറുമ്പ് (Ant)" },
    { general: "ജീവി (Creature)", specific: "പാമ്പ് (Snake)" },
    { general: "ജീവി (Creature)", specific: "മീൻ (Fish)" },
    { general: "മരം (Tree)", specific: "തെങ്ങ് (Coconut Tree)" },
    { general: "മരം (Tree)", specific: "മാവ് (Mango Tree)" },
    { general: "മരം (Tree)", specific: "പ്ലാവ് (Jackfruit Tree)" },
    { general: "പൂവ് (Flower)", specific: "താമര (Lotus)" },
    { general: "പൂവ് (Flower)", specific: "മുല്ലപ്പൂ (Jasmine)" },
    { general: "പൂവ് (Flower)", specific: "ചെമ്പരത്തി (Hibiscus)" },
    { general: "പ്രകൃതി (Nature)", specific: "മഴ (Rain)" },
    { general: "പ്രകൃതി (Nature)", specific: "പുഴ (River)" },
    { general: "പ്രകൃതി (Nature)", specific: "കടൽ (Sea)" },
    { general: "പ്രകൃതി (Nature)", specific: "മല (Mountain)" },
    { general: "പ്രകൃതി (Nature)", specific: "വെയിൽ (Sunlight)" },

    // Objects
    { general: "വാഹനം (Vehicle)", specific: "ബസ് (Bus)" },
    { general: "വാഹനം (Vehicle)", specific: "ഓട്ടോറിക്ഷ (Auto Rickshaw)" },
    { general: "വാഹനം (Vehicle)", specific: "കാർ (Car)" },
    { general: "വാഹനം (Vehicle)", specific: "സൈക്കിൾ (Bicycle)" },
    { general: "വാഹനം (Vehicle)", specific: "തീവണ്ടി (Train)" },
    { general: "വാഹനം (Vehicle)", specific: "വിമാനം (Airplane)" },
    { general: "വാഹനം (Vehicle)", specific: "വള്ളം (Boat)" },
    { general: "വസ്തു (Object)", specific: "കുട (Umbrella)" },
    { general: "വസ്തു (Object)", specific: "പേന (Pen)" },
    { general: "വസ്തു (Object)", specific: "പുസ്തകം (Book)" },
    { general: "വസ്തു (Object)", specific: "കണ്ണട (Spectacles)" },
    { general: "വസ്തു (Object)", specific: "വാച്ച് (Watch)" },
    { general: "വസ്തു (Object)", specific: "ഫോൺ (Phone)" },
    { general: "ഗൃഹോപകരണം (Furniture)", specific: "കസേര (Chair)" },
    { general: "ഗൃഹോപകരണം (Furniture)", specific: "മേശ (Table)" },
    { general: "ഗൃഹോപകരണം (Furniture)", specific: "കട്ടിൽ (Bed)" },
    { general: "ആയുധം (Tool/Weapon)", specific: "കത്തി (Knife)" },
    { general: "ആയുധം (Tool/Weapon)", specific: "മഴു (Axe)" },
    { general: "ആയുധം (Tool/Weapon)", specific: "ചൂൽ (Broom)" },
    { general: "വസ്ത്രം (Clothing)", specific: "മുാണ്ട് (Mundu)" },
    { general: "വസ്ത്രം (Clothing)", specific: "സാരി (Saree)" },
    { general: "വസ്ത്രം (Clothing)", specific: "ഷർട്ട് (Shirt)" },
    { general: "ശരീരഭാഗം (Body Part)", specific: "കണ്ണ് (Eye)" },
    { general: "ശരീരഭാഗം (Body Part)", specific: "കൈ (Hand)" },
    { general: "ശരീരഭാഗം (Body Part)", specific: "കാൽ (Leg)" },
    { general: "ശരീരഭാഗം (Body Part)", specific: "തല (Head)" },
    { general: "ശരീരഭാഗം (Body Part)", specific: "മൂക്ക് (Nose)" },

    // Places & Culture
    { general: "സ്ഥലം (Place)", specific: "കേരളം (Kerala)" },
    { general: "സ്ഥലം (Place)", specific: "ഇന്ത്യ (India)" },
    { general: "സ്ഥലം (Place)", specific: "കൊച്ചി (Kochi)" },
    { general: "സ്ഥലം (Place)", specific: "തിരുവനന്തപുരം (Trivandrum)" },
    { general: "സ്ഥലം (Place)", specific: "മൂന്നാർ (Munnar)" },
    { general: "സ്ഥലം (Place)", specific: "ശബരിമല (Sabarimala)" },
    { general: "സ്ഥലം (Place)", specific: "ഗുരുവായൂർ (Guruvayoor)" },
    { general: "സ്ഥലം (Place)", specific: "വീട് (House)" },
    { general: "സ്ഥലം (Place)", specific: "സ്കൂൾ (School)" },
    { general: "സിനിമ (Movie)", specific: "ദൃശ്യം (Drishyam)" },
    { general: "സിനിമ (Movie)", specific: "മണിച്ചിത്രത്താഴ് (Manichitrathazhu)" },
    { general: "സിനിമ (Movie)", specific: "പ്രേമം (Premam)" },
    { general: "സിനിമ (Movie)", specific: "പുലിമുരുകൻ (Pulimurugan)" },
    { general: "നടൻ (Actor)", specific: "മോഹൻലാൽ (Mohanlal)" },
    { general: "നടൻ (Actor)", specific: "മമ്മൂട്ടി (Mammootty)" },
    { general: "നടൻ (Actor)", specific: "പൃഥ്വിരാജ് (Prithviraj)" },
    { general: "കല (Art)", specific: "കഥകളി (Kathakali)" },
    { general: "കല (Art)", specific: "മോഹിനിയാട്ടം (Mohiniyattam)" },
    { general: "കല (Art)", specific: "ചെണ്ട (Chenda)" },
    { general: "ഉത്സവം (Festival)", specific: "ഓണം (Onam)" },
    { general: "ഉത്സവം (Festival)", specific: "വിഷു (Vishu)" },
    { general: "ഉത്സവം (Festival)", specific: "ക്രിസ്മസ് (Christmas)" },
    { general: "ഉത്സവം (Festival)", specific: "തൃശ്ശൂർ പൂരം (Thrissur Pooram)" },
    { general: "കായികം (Sport)", specific: "ഫുട്ബോൾ (Football)" },
    { general: "കായികം (Sport)", specific: "ക്രിക്കറ്റ് (Cricket)" },
    { general: "കായികം (Sport)", specific: "വള്ളംകളി (Boat Race)" },
    { general: "തൊഴിൽ (Job)", specific: "ഡോക്ടർ (Doctor)" },
    { general: "തൊഴിൽ (Job)", specific: "ടീച്ചർ (Teacher)" },
    { general: "തൊഴിൽ (Job)", specific: "പോലീസ് (Police)" },
    { general: "നിറം (Color)", specific: "ചുവപ്പ് (Red)" },
    { general: "നിറം (Color)", specific: "നീല (Blue)" },
    { general: "നിറം (Color)", specific: "പച്ച (Green)" },
    { general: "നിറം (Color)", specific: "മഞ്ഞ (Yellow)" },
    { general: "ബന്ധം (Relation)", specific: "അമ്മ (Mother)" },
    { general: "ബന്ധം (Relation)", specific: "അച്ഛൻ (Father)" },
    { general: "ബന്ധം (Relation)", specific: "സുഹൃത്ത് (Friend)" }
];

export const WORD_LISTS = {
    ENGLISH: ENGLISH_WORD_LIST,
    MALAYALAM: MALAYALAM_WORD_LIST
};